"use client";

import Image from "next/image";
import { useEffect, useState } from "react";

const projects = [
  { title: "Oracle NetSuite", type: "Web Design Specialist · Aug 2021 — Present", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=85", tone: "bg-[#b9d6db]" },
  { title: "Freelance", type: "WP Front-End Developer & Project Manager · Apr 2019 — Present", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=85", tone: "bg-[#d7c9e8]" },
  { title: "R6 Digital & AWORK", type: "WP Front-End Developer · Aug 2019 — Jun 2020", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=85", tone: "bg-[#e6d3b5]" },
];

function Arrow() { return <span aria-hidden="true" className="ml-2 inline-block text-xl transition-transform group-hover:translate-x-1">↗</span>; }

export default function Home() {
  const [dark, setDark] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { const stored = localStorage.getItem("theme"); const useDark = stored ? stored === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches; setDark(useDark); document.documentElement.classList.toggle("dark", useDark); }, []);
  const changeTheme = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); localStorage.setItem("theme", next ? "dark" : "light"); };
  return <main className="overflow-hidden">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-ink/10 bg-paper/85 px-6 py-4 backdrop-blur-md dark:border-white/10 dark:bg-[#171916]/85 md:px-12">
      <div className="mx-auto flex max-w-7xl items-center justify-between"><a href="#top" className="font-serif text-2xl font-bold tracking-tight">gapsdev<span className="text-peach">.</span></a><div className="hidden items-center gap-8 text-xs font-bold uppercase tracking-[.14em] md:flex"><a href="#work" className="hover:text-peach">Work</a><a href="#about" className="hover:text-peach">About</a><a href="#contact" className="hover:text-peach">Contact</a></div><div className="flex items-center gap-4"><button onClick={changeTheme} aria-label="Toggle color theme" className="grid h-9 w-9 place-items-center rounded-full border border-ink/15 text-sm dark:border-white/20">{dark ? "☼" : "◐"}</button><button onClick={() => setMenuOpen(!menuOpen)} className="text-xs font-bold uppercase tracking-widest md:hidden">Menu</button></div></div>
      {menuOpen && <div className="flex flex-col gap-4 pt-5 text-sm font-bold uppercase tracking-widest md:hidden"><a onClick={() => setMenuOpen(false)} href="#work">Work</a><a onClick={() => setMenuOpen(false)} href="#about">About</a><a onClick={() => setMenuOpen(false)} href="#contact">Contact</a></div>}
    </nav>

    <section id="top" className="grid-lines relative min-h-screen px-6 pb-12 pt-32 md:px-12 md:pt-40"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-16"><p className="text-xs font-bold uppercase tracking-[.2em] text-ink/55 dark:text-white/55">Front-end Developer · Cabagan, Isabela, PH · Available for select work</p><div><h1 className="max-w-6xl font-serif text-[18vw] leading-[.78] tracking-[-.07em] md:text-[10.5rem] lg:text-[13rem]">Building thoughtful <em className="font-normal text-peach">web</em><br />experiences.</h1><div className="mt-12 flex flex-col justify-between gap-6 border-t border-ink/15 pt-5 dark:border-white/15 md:flex-row"><p className="max-w-sm text-sm leading-6 text-ink/70 dark:text-white/70">Sheera Mae Beltran is a front-end developer and WordPress specialist who builds responsive, high-performing websites.</p><a href="#work" className="group text-sm font-bold uppercase tracking-[.13em]">See experience <Arrow /></a></div></div><div className="flex items-end justify-between"><span className="text-xs tracking-widest text-ink/55 dark:text-white/55">SCROLL TO EXPLORE</span><span className="font-serif text-5xl italic text-moss dark:text-[#aebf9e]">01—04</span></div></div></section>

    <section id="about" className="bg-ink px-6 py-24 text-paper dark:bg-[#242923] md:px-12 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-peach">Hello, I&apos;m Sheera</p><p className="mt-7 max-w-xs font-serif text-3xl leading-tight">A detail-focused developer who cares about websites that work beautifully for everyone.</p></div><div><p className="font-serif text-4xl leading-[1.12] tracking-tight md:text-6xl">I turn designs into <em className="text-peach">responsive</em>, accessible, and high-performing digital experiences.</p><div className="mt-14 grid grid-cols-2 gap-8 border-t border-white/15 pt-6 text-sm"><div><span className="block font-serif text-4xl text-peach">5+</span><span className="mt-2 block text-white/60">years in web development</span></div><div><span className="block font-serif text-4xl text-peach">2021</span><span className="mt-2 block text-white/60">at Oracle NetSuite</span></div></div></div></div></section>

    <section className="px-6 py-24 md:px-12 md:py-32"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-peach">Core skills</p><h2 className="mt-3 font-serif text-5xl tracking-tight md:text-7xl">Build with intent.</h2></div><span className="hidden font-serif text-5xl italic text-moss dark:text-[#aebf9e] md:block">02—04</span></div><div className="border-t border-ink/15 dark:border-white/15">{[["01", "Front-end development", "HTML5, CSS3, JavaScript, responsive design, and mobile-first implementation."], ["02", "WordPress", "Custom themes, builders, customization, SEO best practices, and basic PHP/theme editing."], ["03", "Web delivery", "Figma and Adobe XD implementation, performance optimization, QA, Git, and cross-browser compatibility."]].map(([n, title, copy]) => <div key={n} className="group grid gap-3 border-b border-ink/15 py-7 dark:border-white/15 md:grid-cols-[100px_1fr_1fr] md:items-center"><span className="text-xs text-ink/50 dark:text-white/50">{n}</span><h3 className="font-serif text-3xl transition-colors group-hover:text-peach md:text-5xl">{title}</h3><p className="text-sm text-ink/60 dark:text-white/60">{copy}</p></div>)}</div></div></section>

    <section id="work" className="bg-[#e7ded2] px-6 py-24 dark:bg-[#20251f] md:px-12 md:py-32"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-peach">Professional experience</p><h2 className="mt-3 font-serif text-5xl tracking-tight md:text-7xl">Where I&apos;ve built.</h2></div><a href="#contact" className="group hidden text-sm font-bold uppercase tracking-[.13em] md:block">Start a project <Arrow /></a></div><div className="grid gap-10 md:grid-cols-2">{projects.map((project, i) => <article key={project.title} className={i === 2 ? "md:col-span-2 md:grid md:grid-cols-2 md:gap-10" : ""}><a href="#contact" className={`image-hover group block overflow-hidden ${project.tone} ${i === 2 ? "aspect-[1.3/1]" : "aspect-[.92/1]"}`}><Image src={project.image} alt={project.title} width={1000} height={900} className="h-full w-full object-cover mix-blend-multiply" /></a><div className="mt-4 flex items-start justify-between"><div><h3 className="font-serif text-2xl">{project.title}</h3><p className="mt-1 text-xs uppercase tracking-wider text-ink/55 dark:text-white/55">{project.type}</p></div><span className="text-xl">↗</span></div></article>)}</div></div></section>

    <section className="px-6 py-24 md:px-12 md:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-peach">How I work</p><div className="mt-10 grid gap-7 md:grid-cols-2"><div className="rounded-sm bg-moss p-8 text-paper shadow-soft md:p-11"><span className="font-serif text-6xl text-peach">01</span><p className="mt-2 font-serif text-3xl leading-tight">Start with the real problem, not the first feature request.</p><p className="mt-10 text-sm leading-6 text-white/60">Clear goals, quick prototypes, and early feedback make the best use of everyone&apos;s time.</p></div><div className="rounded-sm border border-ink/15 p-8 dark:border-white/15 md:p-11"><span className="font-serif text-6xl text-peach">02</span><p className="mt-2 font-serif text-3xl leading-tight">Ship a focused first version, then make it better with evidence.</p><p className="mt-10 text-sm leading-6 text-ink/55 dark:text-white/55">The work is transparent, iterative, and grounded in what people actually need.</p></div></div></div></section>

    <footer id="contact" className="bg-peach px-6 py-20 text-ink md:px-12 md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em]">Have a project in mind?</p><a href="mailto:gapsdeveloper@gmail.com" className="group mt-5 inline-block font-serif text-[12vw] leading-none tracking-[-.06em] md:text-[8rem]">Let&apos;s build it<span className="inline-block transition-transform group-hover:translate-x-3">↗</span></a><div className="mt-20 flex flex-col justify-between gap-5 border-t border-ink/20 pt-5 text-xs font-bold uppercase tracking-widest md:flex-row"><span>© {new Date().getFullYear()} Sheera Mae Beltran</span><div className="flex gap-6"><a href="https://www.linkedin.com/in/gapsdev/" target="_blank" rel="noreferrer">LinkedIn</a><a href="mailto:gapsdeveloper@gmail.com">Email</a><a href="tel:+639479781283">+63 947 978 1283</a></div><a href="#top">Back to top ↑</a></div></div></footer>
  </main>;
}
